const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR  ";
const USER_LOADING = "USER_LOADING";
const USER_LOADED = "USER_LOADED";

export {
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  USER_LOADING,
  USER_LOADED,
  REGISTER_SUCCESS,
  REGISTER_ERROR
};
